### ISSUE TITLE
What is the difference between monolithic and microservice architecture?

### ISSUE THREAD

**Issue by MohammadrezaAhmadii** [hamed-shirbandi/TaskoMask#49]
Hello hamed, what is the difference between microservice architecture and monolithic architecture and when is it better to use which architecture?

**Comment by hamed-shirbandi** [comment]
Hi @MohammadrezaAhmadii
There are plenty of resources around the web that you can find for your questions. But here are some quick tips you may like:

## Monolithic Architecture
A monolithic architecture holds all the services in a single solution, your development team work on a single shared codebase and your deployment team deploy it as a single service.

### Monolithic Benefits:

> **In development environment** : 
> - All services develop by a single back-end language.
> - All services work with a single database, and it is easy to collect data trough queries.
> - Transactions are guarantied behind some tools like an ORM.

> **In testing environment** : 
> - Test all services and their communication
> - No Black-Box testing
> - Defect localization is easy during the E2E tests

> **In deployment environment** : 
> - Easy to publish the software just like copy and paste it on the production server
> - Easy to monitor
> - Easy to scale by running multiple copies of the application behind a load balancer


### Monolithic Drawbacks:

> - **In development environment** : 
> - Serious problems with developing a large code base
> - Hard to perform changes because of tight coupling between services.
> - Hard to maintain.
> - Tech stack limitation.
> - Hard to protect data behind the rules because of accessibility of data through all services.
> - Hard to onboard new developers and scale the development team

> **In testing environment** : 
> - Hard to maintain because of the large scale code base (tests are code)

> **In deployment environment** : 
> - Late delivery of new features
> - Inability to allocate resources to services as much as they need
> - Partition intolerance


## Microservices Architecture
It defines an architecture that structures the application as a set of loosely coupled, collaborating services. Each service has its own solution.

### Microservices Benefits :

> **In development environment** : 
> - Each service is small enough and easy to develop and maintain
> - Each service can use its prefer back-end language.
> - Each service has its own database and data is guarantied behind the service rules.
> - Easy to perform changes without effecting on another services.
> - Easy to scale the development team and onboard new developers.

> **In testing environment** : 
> - Easy to maintain the test codes.
> - Each service is tested separately.

> **In deployment environment** : 
> - Quick delivery of new features
> - Ability to allocate resources to services as much as they need
> - Partition tolerance


### Microservices Drawbacks:

> **In development environment** : 
> - Hard to support distributed transactions.
> - Hard to collect data trough services during the queries.
> - Dealing with complexities of new patterns and tools.
> - Hard to find people with high degree of requirement knowledge.


> **In testing environment** : 
> - Hard to test the features that need collaboration between some services.
> - Defect localization is hard during the E2E tests
> - Black-Box testing

> **In deployment environment** : 
> - Complexities of deploying
> - Complexities of monitoring
> - Complexity of deployment tools and technologies


## When to use which one of them?
As a software engineer we must consider the Time, Scale and Trade-Offs in all of our decisions, even about adding a small feature to an existing app or about choosing an architecture and build up a development team.

### Time
If the time of living of the app is not going to be so long, it doesn't need to always looking for the best solution or adding the complexities to the software development.
If you are in a situation that can't estimate the time of living, for example if you are lunching a startup, it is better to start with monolith and consider that this is software development, and we always have the possibility of refactoring.

### Scale
If your environment is not ready for scale, both on development and deployment, so why start with Microservices? It needs much more resources than monolith (people, computers, money, time, etc.)

### Trade-Offs
Thinking about the goal and what we already have to reach it. Think about your resources. How many people do you have in your team? How much time do you have to deliver the first stable version? How much money do you have? What are your short goals and long goals? How many visitors going to visit your app at the first? How much increase for six months later?

So, by considering the above parameters, you can find the better choice for your software architecture. Each decision has its own benefits and drawbacks, you may have to consider many other parameters, it could be very risky. But this is the kind of works a Software Engineer must do.
After all trade-offs and considerations, If you choose Monolith, don't be shy and don't mind what the community say, they might choose microservices because it's cool!

**Comment by MohammadrezaAhmadii** [comment]
What features are needed to turn monolithic architecture into microservices architecture?

**Comment by hamed-shirbandi** [comment]
I assume that :
- Your product business is complex
- You are at the design phase
- You are going to start with Monolithic and then refactor it to Microservices in the near future

Then with this approach, it is better to follow DDD concepts and separate your services into some subdomains and implement them using DDD strategic and tactical design concepts like BC, Aggregate, etc.

It helps you to prevent tight coupling between services and make them ready to separate in different solutions.

In the refactor phase, you can follow the Strangler application pattern to extract your services from the current monolith. Also in this step you will find common infrastructure and cross-cutting concepts and move them to Building Blocks to share them between all services.

There are many other tips following your case and need to see the situation. But if you have any question, you are always welcome to ask.
